authors = ["Warren Schweigert"]
name = "StructuralInheritance"
uuid = "8444d97c-b5e1-11e8-1bb1-4d91caf0c934"
version = "0.0.1"
license = "MIT"



[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
